image: registry.gitlab.com/remipassmoilesel/gitsearch/ci-image:0.6

variables:
  GOCACHE: "$CI_PROJECT_DIR/.go-cache"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

cache:
  key: global
  paths:
    - .go-cache
    - .yarn-cache
    - web-client/node_modules

stages:
  - build

build before merge:
  stage: build
  script:
    - ./_ci.sh
  only:
    - merge_requests
  artifacts:
    paths:
      - gitsearch-linux
      - gitsearch-macos
      - gitsearch-windows
    expire_in: 1 week

build master:
  stage: build
  script:
    - ./_ci.sh
  only:
    - master
  artifacts:
    paths:
      - gitsearch-linux
      - gitsearch-macos
      - gitsearch-windows
    expire_in: 1 month