image: registry.gitlab.com/remipassmoilesel/gitsearch/ci-image:0.1

variables:
  GOCACHE: "$CI_PROJECT_DIR/.go-cache"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

cache:
  key: global
  paths:
    - .go-cache
    - .yarn-cache
    - web-client/node_modules

stages:
  - build

build:
  stage: build
  script:
    - ./scripts/ci.sh

